version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=hawkstatus
      - POSTGRES_USERNAME=hawkstatus
      - POSTGRES_USER=hawkstatus
      - POSTGRES_PASSWORD=hawkstatus
    ports:
      - 5432:5432
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=hawkstatus
      - RABBITMQ_DEFAULT_PASS=hawkstatus
    ports:
      - 5672:5672
      - 15672:15672
  smtp:
    restart: always
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
