version: '3'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  postgres-gateway:
    image: postgres
    container_name: postgres-gateway
    restart: always
    user: postgres
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DB=gateway
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 5432:5432
    healthcheck:
      test: [CMD, pg_isready]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-scheduler:
    image: postgres
    container_name: postgres-scheduler
    restart: always
    user: postgres
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DB=schedules
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 5433:5432
    healthcheck:
      test: [CMD, pg_isready]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-processor:
    image: postgres
    container_name: postgres-processor
    restart: always
    user: postgres
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DB=processes
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - 5434:5432
    healthcheck:
      test: [CMD, pg_isready]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  postgres-password:
    file: postgres-password.txt
